config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  
  resources :courses do
   member do
      get 'general'
   end
   resources :students, only: [:index]

	 resources :tests , except: [:show] do
      member do
        get 'add_grades'
      end
  	 	#resources :grades
  	 	
  	 	
  	 end
  end
  resources :students

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  "courses#index"
end

app/views/layouts/_forms.html.erb
<div class="container-fluid">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cursadas Ruby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag    'starter-template', media: 'all' %>
    
  </head>

  <body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Gestor de notas</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Cursadas", courses_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Estudiantes", students_path, class: 'nav-link' %>
          </li>
          <!--li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Configuración</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <%= link_to "Cursadas", courses_path, class: 'dropdown-item' %>
              <%= link_to "Estudiantes", students_path, class: 'dropdown-item' %>
              <%#= link_to "Notas", grades_path, class: 'dropdown-item' %>
            </div>
          </li-->
          
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cuenta</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <%= link_to 'Perfil', edit_user_registration_path, :class => 'dropdown-item' %>
              <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
            </div>
          <% else %>
          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cuenta</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
            <%= link_to "Registrar", new_user_registration_path, :class => 'dropdown-item'  %>
            <%= link_to "Acceder", new_user_session_path, :class => 'dropdown-item'  %>
          <% end %>
          </li>
        </ul>
        <% if user_signed_in? %>
            <span class="text-primary"><%= current_user.email %></span>
        <% end %>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="starter-template">

        <%= yield %>
      </div>
    </main><!-- /.container -->
  </body>
</html>